server:
  host: 0.0.0.0
  port: 8080
debug: true
log_level: debug

database:
  host: template-db
  port: 5432
  user: user
  password: password
  dbname: mydb

redis:
  address: template-redis:6379
  password: 
  user:
  db: 0
  max_retries: 3