server:
  host: 0.0.0.0
  port: 8080
debug: true
log_level: debug

database:
  host: template-db
  port: 5432
  user: user
  password: password
  db_name: mydb
  secure: false

redis:
  address: template-redis
  # password: 
  # user:
  db: 0
  max_retries: 3
  dial_timeout: 30
  timeout: 30